networks:
  vlad-yakovlev-dev:
    name: vlad-yakovlev-dev

services:
  nginx:
    image: nginxproxy/nginx-proxy:latest
    pull_policy: always
    networks:
      - vlad-yakovlev-dev
    ports:
      - 80:80
      - 443:443
    environment:
      ENABLE_IPV6: true
    volumes:
      - $PWD/conf:/etc/nginx/conf.d
      - $PWD/vhost:/etc/nginx/vhost.d
      - $PWD/html:/usr/share/nginx/html
      - $PWD/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always

  nginx-acme:
    image: nginxproxy/acme-companion:latest
    pull_policy: always
    networks:
      - vlad-yakovlev-dev
    environment:
      - DEFAULT_EMAIL=vlad309523@gmail.com
    volumes_from:
      - nginx
    volumes:
      - $PWD/certs:/etc/nginx/certs:rw
      - $PWD/acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
